### ISSUE TITLE
Checksum error when calling file command multiple times

### ISSUE THREAD

**Issue by murtosl** [opscode/chef#2697]
class Chef
	class Provider
		class JailkitChrootsh < Chef::Provider::LWRPBase   
    ... 
         def write_chrootsh(chroot)
				file @iniPath do
					content chroot
					user 'root'
					group 'root'
					mode 0644
				end
			end
                end end end 
This code is replacing a settings file that already exists. It will work, especially in stand alone cookbooks calling it.

If this code is also called from another cookbook as well, and those cookbooks are called together in a build (say the role uses both of them in the run list, but they aren't calling each other) then it will throw the following error:

        Error executing action `create` on resource 'file[/etc/jailkit/jk_chrootsh.ini]'       
              
    Chef::Exceptions::ChecksumMismatch       
    ----------------------------------       
    Checksum on resource (f93fe4) does not match checksum on content (ffa888)       
           
    Resource Declaration:       
    ---------------------       
    # In /tmp/kitchen/cache/cookbooks/jailkit/libraries/provider_jailkit_chroot.rb       
           
    105: 				file '/etc/jailkit/jk_chrootsh.ini' do       
    106: 					content chroot       
    107: 		       			user 'root'
           108: 
       					group 'root'
           109: 
       					mode 0644
           
       110: 				end
           111: 			end
           
           Compiled Resource:
    Declared in /tmp/kitchen/cache/cookbooks/jailkit/libraries/provider_jailkit_chroot.rb:105:in `write_chrootsh'       
           
           file("/etc/jailkit/jk_chrootsh.ini") do
             action "create"
             updated true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             path "/etc/jailkit/jk_chrootsh.ini"
             backup 5
             atomic_update true
       
             diff "--- /etc/jailkit/jk_chrootsh.ini\t2014-12-17 20:00:43.261171048 +0000\\n+++ /etc/jailkit/.jk_chrootsh.ini20141217-15608-1nq3fjb\t2014-12-17 20:01:15.307439037 +0000\\n@@ -1,9 +1,3 @@\\n-## example for a user\\n-#[test]\\n-#env= DISPLAY, XAUTHORITY\\n-#\\n-##example for a group, there should be only 1 space inbetween the words!\\n-#[group users]\\n-#env = DISPLAY, XAUTHORITY\\n-#\\n+[user1]\\n+env = PATH, LANG, LANGUAGE, NODE_PATH, TERM"
       
             declared_type :file
             cookbook_name "Cookbook2"
       
             content "[user1]\nenv = PATH, LANG, LANGUAGE, NODE_PATH, TERM\n[user2]\nenv = PATH, LANG, LANGUAGE, NODE_PATH, TERM\n"
             owner "root"
             group "root"
             mode 420

    checksum "f93fe408083baf999b89c34dea84af08f67e73f94da3f37ef8ebd900551b4128"       
           end
           
       
User1 would have been inserted in Cookbook1, and User2 is added in CookBook2, which is the cookbook that threw this error.

It works in chef 11. I know you've added checksum stuff to chef 12, but this isn't a call from remote_file: chef made (or at least wrote over) the file.  The content is generated from the the code running in that class (not shown). As I said, it works until you try it in two separated cookbooks on the same box. Deleting the file before creating it doesn't fix anything.

I have worked around this by using Chef::Util::FileEdit to rewrite the file instead; but am not sure why the issue came up in the first place. Sorry if I'm just not understanding what's going on with the checksum.

**Comment by tyler-ball** [comment]
I agree with @lamont-granquist - use notifications or the definition example (I think the exact section he is talking about is http://docs.chef.io/definitions.html#many-recipes-one-definition) when you need to modify the same file from multiple recipes.

I think this issue would happen regardless of whether the resource was cloned or not - the issue is that the same file is edited multiple times in the chef run.

(compile phase)
1. File `a` is unziped with checksum 123
2. Resource `file[a]` is created and reads checksum 123 from file on disc
3. Resource `file[a]` is seen and cloned from existing resource, clones or reads checksum 123
(converge phase)
4. First resource `file[a]` converges and updates checksum to 456
5. Second resource `file[a]` tries to modify the file but it doesn't have the expected checksum (123)

I'm going to close because I believe the right fix is to only create 1 resource and update it after all its contents are converged.  @murtosl Does this work for you?

**Comment by murtosl** [comment]
That's fine, thanks for the explaination.
