### ISSUE TITLE
How to use Chef "search" method in library code 

### ISSUE THREAD

**Issue by RayAtBloomberg** [opscode/chef#2743]
Hello,

I encountered a problem about using "search" method in library code:
libraries/helpers.rb
```
Bcpc
  Helper
    Extends self
    Def help
      search(:node, "....")
    end
  end
end
```
Then use this module method in recipes like this:
Bcpc::Helper.help
When I run it, it report the error that search method is not defined in Bcpc::Helper:Module

I found the search method is defined in Chef::Search::Query class. Then I tried use the full name of search in my library code like: Chef::Search::Query.search(:node, "....").
But it reported search is undefined in Chef::Search::Query. 
Should this search method be a static method that can be called with its class name?

How can I use the Chef provided "search" method in my library code in this case?
Thanks!

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
